version: '3'
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.11.1
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: "service:mainserver"
    depends_on:
    - mainserver

  mainserver:
    image: ikubernetes/mini-http-server:v0.3
    networks:
      envoymesh:
        aliases:
        - webserver
        - httpserver

networks:
  envoymesh: {}
